### ISSUE TITLE
test script

### ISSUE THREAD

**Issue by ShChen233** [Cccccczh404/H-SAM#1]
![image](https://github.com/Cccccczh404/H-SAM/assets/143151549/a5ec4d08-05d0-4428-933f-57497201671d)
![image](https://github.com/Cccccczh404/H-SAM/assets/143151549/a697b80e-b139-4c2e-85e9-ac08ec96c5ba)
![image](https://github.com/Cccccczh404/H-SAM/assets/143151549/026a1f46-0d9b-4fec-90d4-b0e7c4b887b5)

如图，我下载了https://drive.google.com/file/d/1A1wqTT_FD6FXzqCj9LNStxT425ZfYpnE/view这里的预训练权重来对Synapse数据集上进行测试，但是性能非常差。而且也是直接运行test.py文件。是否是代码未及时更新？

**Comment by Cccccczh404** [comment]
![image](https://github.com/Cccccczh404/H-SAM/assets/152238377/578fe212-ac81-4835-80af-34610ed9c92e)
CUDA_VISIBLE_DEVICES="0" python test.py --is_savenii --lora_ckpt 220_epoch_299.pth --vit_name='vit_b' --ckpt=checkpoints/sam_vit_b_01ec64.pth --stage=3 --img_size=512
你的test script是什么，是否使用--lora_ckpt和--ckpt

**Comment by Cccccczh404** [comment]
> ![image](https://private-user-images.githubusercontent.com/143151549/319129527-a5ec4d08-05d0-4428-933f-57497201671d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTY4ODcsIm5iZiI6MTcxMjE1NjU4NywicGF0aCI6Ii8xNDMxNTE1NDkvMzE5MTI5NTI3LWE1ZWM0ZDA4LTA1ZDAtNDQyOC05MzNmLTU3NDk3MjAxNjcxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxNTAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTI3YmZkNDdlYjViZWZiZWFmZDYyMTQzZTg4YmI0ZGE5YTM1Yzc4MmViZjg4YjM4ZDQ3NmY0YzQ4N2YyZjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.908D1eDsYHjCCKUuW1784kylPlhHlmRusO5W4k8rfhs) ![image](https://private-user-images.githubusercontent.com/143151549/319129575-a697b80e-b139-4c2e-85e9-ac08ec96c5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTY4ODcsIm5iZiI6MTcxMjE1NjU4NywicGF0aCI6Ii8xNDMxNTE1NDkvMzE5MTI5NTc1LWE2OTdiODBlLWIxMzktNGMyZS04NWU5LWFjMDhlYzk2YzViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxNTAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmExMjVlNGE1ZmFiN2IwMmU5MGQ0YmY2OWY2ZWRmNTk3ZDg0NjA4MjkxNmJhNDk3ZTJjNGFlNDE4MDg4MzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8savVogMsIbsTxqrdLHZphto42sqeZERZegQYIlDoig) ![image](https://private-user-images.githubusercontent.com/143151549/319130286-026a1f46-0d9b-4fec-90d4-b0e7c4b887b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTY4ODcsIm5iZiI6MTcxMjE1NjU4NywicGF0aCI6Ii8xNDMxNTE1NDkvMzE5MTMwMjg2LTAyNmExZjQ2LTBkOWItNGZlYy05MGQ0LWIwZTdjNGI4ODdiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxNTAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDg0YjI1ZDcxZmEyNGUxYTM1OWI0M2JhNjY5ZGI1ZTAyOGYxMzdjOGZmN2M1NjQyZTAwMTA0ZWU4NDMyMmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bzp6lPwozcZFgSogWPwHAT86MuFe41_SQ515uPrqvYI)
> 
> 如图，我下载了[https://drive.google.com/file/d/1A1wqTT_FD6FXzqCj9LNStxT425ZfYpnE/view这里的预训练权重来对Synapse数据集上进行测试，但是性能非常差。而且也是直接运行test.py文件。是否是代码未及时更新？]

![image](https://github.com/Cccccczh404/H-SAM/assets/152238377/96f12a60-7ac4-4405-8e88-590543f07b2b)
CUDA_VISIBLE_DEVICES="0" python test.py --is_savenii --lora_ckpt 220_epoch_299.pth --vit_name='vit_b' --ckpt=checkpoints/sam_vit_b_01ec64.pth --stage=3 --img_size=512
你的test script是什么，是否使用--lora_ckpt和--ckpt

**Comment by ShChen233** [comment]
![image](https://github.com/Cccccczh404/H-SAM/assets/143151549/4305062d-2bb2-4196-b116-96c5ce76f330)
虽然不是命令行形式，但是修改了相应文件的args参数，并直接运行

**Comment by ShChen233** [comment]
找到原因了，是我使用了另一个项目中下载的数据集。但仅仅只是初等变换，模型性能就下降如此之大，其泛化性能是否真的深思？https://drive.google.com/file/d/18XGakRzcZ3_BZKeF_CUljIZj3edc3Ah9/view?usp=drive_link
