### ISSUE TITLE
About Transformer decoder Pixel decoder

### ISSUE THREAD

**Issue by zzzyzh** [Cccccczh404/H-SAM#11]
Hi,
Unfortunately, I didn't find your email address as the author, so I had to ask a dissertation-related question here

Which structure of SAM's mask decoder does the Transformer decoder and pixel decoder mentioned in the paper refer to? Because I don't think SAM should have the ability to assign a class to each pixel?

If so, you can send it to me directly at zzzyzh@bupt.edu.cn. Looking forward to further communication with you!

**Comment by Cccccczh404** [comment]
Sure! I will contact you through my email: billycheng@outlook.com
