### ISSUE TITLE
Reproduced performance on Synapse multi-organ CT dataset are poor

### ISSUE THREAD

**Issue by nguyenpbui** [Cccccczh404/H-SAM#12]
Dear authors,

Thank you for the awesome work.

I am reproducing your results but the Dice scores of 8 classes dropped significantly, ~2%, as shown in the attached figure.

![image](https://github.com/Cccccczh404/H-SAM/assets/34409468/f4a9794a-ab85-4b38-b726-097d27c47582)

Do you have any ideas or suggestions for me?

Best regards.

**Comment by Cccccczh404** [comment]
Thanks for your interest! Based on my experience, tuning hyperparameters like --base_lr and --warmup_period during training could be helpful. Some training strategies to raise the sampling probability of slices with tail class organs can also work.
