### ISSUE TITLE
Synapse多器官分割数据集

### ISSUE THREAD

**Issue by ncp-nice** [Cccccczh404/H-SAM#13]
作者大大，我想请问一下，我的模型输入的train和test的label都需要是onehot格式的mask的png，我应该怎么处理Synapse多器官分割数据集呢？

**Comment by ncp-nice** [comment]
把他们都切片，单独根据像素分离出来一个标签好麻烦呀，而且哪个标签像素代表哪个器官我也不清楚

**Comment by Cccccczh404** [comment]
你好！根据你的描述，不知道这一段代码对你有没有帮助？
utils.py
![image](https://github.com/Cccccczh404/H-SAM/assets/152238377/61f0ff0a-6b61-45c3-8b01-e7e25f872cdd)
