### ISSUE TITLE
promise12和LA的HD指标

### ISSUE THREAD

**Issue by ShChen233** [Cccccczh404/H-SAM#16]
您好，可以提供一下promise12和LA数据集中的HD指标吗
![image](https://github.com/user-attachments/assets/af6703b8-577d-486f-80cc-8b8cf25987aa)

**Comment by Cccccczh404** [comment]
During experiment we only provided HD score for fully supervised results
![image](https://github.com/user-attachments/assets/a7b69df5-857e-4579-ab4c-b213ba410b9d)
