### ISSUE TITLE
两类分割结果很差

### ISSUE THREAD

**Issue by Saillxl** [Cccccczh404/H-SAM#17]
我用二分类数据集，预测的结果基本全为黑。请问有人尝试过运行自己的数据集吗？

**Comment by DC-hydrid** [comment]
Have the same problem! Have you solved the problems?

**Comment by Cccccczh404** [comment]
What kind of binary dataset? Since the pretrained model was adapted on multi-organ dataset, it is suggested to fine-tune instead of zero-shot adapting on the new binary dataset.
