### ISSUE TITLE
想问一下作者大大要一下可视化结果的原图~   准备拿来做自己论文的可视化对比

### ISSUE THREAD

**Issue by ncp-nice** [Cccccczh404/H-SAM#18]
![{F87A641C-5FE5-4B20-95C3-4C64A3356326}](https://github.com/user-attachments/assets/19b4ce59-ec20-4337-91d4-92c1474b42d8)
xiangya想要没有箭头的

**Comment by Cccccczh404** [comment]
您好，抱歉这部分原图当时没有保存，但是可视化结果可以直接运行pretrained model然后使用伪色处理获得
