### ISSUE TITLE
Gradient feedback error

### ISSUE THREAD

**Issue by EnKaiZhang** [Cccccczh404/H-SAM#2]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 9, 196]], which is output 0 of IndexPutBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by Cccccczh404** [comment]
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 9, 196]], which is output 0 of IndexPutBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Hello! Can you provide more details for this error? This kind of RuntimeError sometimes occurs when using operations like '+='.

**Comment by EnKaiZhang** [comment]
> > RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 9, 196]], which is output 0 of IndexPutBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> Hello! Can you provide more details for this error? This kind of RuntimeError sometimes occurs when using operations like '+='.

According to the requirements of the training, running it now will encounter this error.

**Comment by EnKaiZhang** [comment]
> > RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 9, 196]], which is output 0 of IndexPutBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> Hello! Can you provide more details for this error? This kind of RuntimeError sometimes occurs when using operations like '+='.

I am using ViT-B.

**Comment by Cccccczh404** [comment]
Thank you for the feedback! The requirements.txt and README.md have been updated. This version should be working.

**Comment by ncp-nice** [comment]
hello，are you resolve this problem？ i also encounter the error
