### ISSUE TITLE
作者您好，为啥我复现出来的结果这么差呀？是哪里设置错了吗？

### ISSUE THREAD

**Issue by CAIAO230017** [Cccccczh404/H-SAM#20]
您的源代码未作任何修改
![94d2d96ae005b3f4f4a004c1d490367](https://github.com/user-attachments/assets/1da06565-9fca-4e16-9c8d-c5c604a9695c)

**Comment by Cccccczh404** [comment]
您好，出现这样的结果是不合理的，同样的代码如果hyperparameter设置的有问题也会出现不合理的结果。
