### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Tzx11** [Cccccczh404/H-SAM#3]
Hello,I am very interested in your work and I have two questions.
1.If I test my dataset, do I also need to convert it to a .npz file
2.Is there a visual code section available

**Comment by Cccccczh404** [comment]
> Hello,I am very interested in your work and I have two questions. 1.If I test my dataset, do I also need to convert it to a .npz file 2.Is there a visual code section available

Thanks for your interests! 
1. You can change the code for data loading in datasets/dataset_synapse.py.
2. Right now a visual code section is not provided.
