### ISSUE TITLE
trainer codes for LA and PROMISE12

### ISSUE THREAD

**Issue by bigfishfour** [Cccccczh404/H-SAM#8]
Hello author, thank you for publishing such an excellent work. Do you have trainer codes for LA and PROMISE12? I only saw trainer_Synapse code

**Comment by Cccccczh404** [comment]
Thank you for your interest! Instruction on trainer codes for LA and PROMISE12 will be updated soon!

**Comment by aijinrjinr** [comment]
Hi, the instructions for training on LA and PROMISE12 dataset as well as the corresponding data preprocessing details have now been updated. Thank you for your patience!

**Comment by Jolieresearch** [comment]
Dear author, I did not find a relevant trainer for the  LA and PROMISE12 datasets.

**Comment by 699zjl** [comment]
作者您好，能否分享一下LA 和PROMISE12两个数据集的train文件，我现在只能训练Synapse数据集，正在学习您的代码，非常期待！！

![Image](https://github.com/user-attachments/assets/0d09787a-9e64-43f8-8893-9cc8d59bacac)

![Image](https://github.com/user-attachments/assets/d0fb7aa7-2241-4606-b085-b4187ee3be00)

![Image](https://github.com/user-attachments/assets/e61e96ef-abe0-4814-8b52-93a9722ae6fb)
